#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Border Colors =============================
# (normal, active): #81aeb6     (focused): #bf4c39
bspc config normal_border_color \#600000
bspc config active_border_color \#600000
bspc config focused_border_color \#ff0000

# Rules ========================================
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart =====================================
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
xscreensaver -no-splash &