"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[\uE0C6 ](bg:red fg:color_grey)\
$directory\
[\uE0C6 ](bg:color_grey fg:red)\
$git_branch\
$git_status\
[\uE0C6 ](fg:color_grey bg:red)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[\uE0C6](bg:none fg:red)\
$line_break$character"""

palette = 'catmocha'

[palettes.yellowverse]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_grey = '#393E46'
color_light_grey = '#B4B4B8'
color_dark_grey = '#222831'

[palettes.catmocha]
color_fg0 = '#fbf1c7'
color_grey = '#393E46'
color_light_grey = '#B4B4B8'
color_dark_grey = '#222831'
black = '#45475A' # surface1
red = '#C70000' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1
purple = '#AC5180' 

[os]
disabled = false
style = "bg:color_grey fg:red"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_grey fg:color_light_grey"
style_root = "bg:color_grey fg:color_light_grey"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_grey"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_grey)]($style)'

[git_status]
style = "bg:color_grey"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_grey)]($style)'

[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[java]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $context) ](fg:#83a598 bg:red)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:red)'
vimcmd_replace_symbol = '[](bold fg:red)'
vimcmd_visual_symbol = '[](bold fg:red)'
